#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fnmatch
from pathlib import Path
import shutil
import stat
import tarfile
import tempfile
import urllib.request
import zipfile

CMAKE_VERSION = "4.4.3"
NINJA_VERSION = "1.13.2"
ZIG_VERSION = "0.16.0"

URLS = {
    "windows": {
        "cmake": f"https://github.com/Kitware/CMake/releases/download/v{CMAKE_VERSION}/cmake-{CMAKE_VERSION}-windows-x86_64.zip",
        "ninja": f"https://github.com/ninja-build/ninja/releases/download/v{NINJA_VERSION}/ninja-win.zip",
        "zig": f"https://ziglang.org/download/{ZIG_VERSION}/zig-x86_64-windows-{ZIG_VERSION}.zip",
    },
    "linux": {
        "cmake": f"https://github.com/Kitware/CMake/releases/download/v{CMAKE_VERSION}/cmake-{CMAKE_VERSION}-linux-x86_64.tar.gz",
        "ninja": f"https://github.com/ninja-build/ninja/releases/download/v{NINJA_VERSION}/ninja-linux.zip",
        "zig": f"https://ziglang.org/download/{ZIG_VERSION}/zig-x86_64-linux-{ZIG_VERSION}.tar.xz",
    },
}

def download(url: str, dst: Path) -> None:
    print(f"[portable] download {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "GekkoAOT-portable-release/1"})
    with urllib.request.urlopen(req) as r, dst.open("wb") as f:
        shutil.copyfileobj(r, f)

def extract(archive: Path, dst: Path) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    if archive.suffix == ".zip":
        with zipfile.ZipFile(archive) as z:
            z.extractall(dst)
    else:
        with tarfile.open(archive, "r:*") as t:
            t.extractall(dst)

def single_root(path: Path) -> Path:
    entries = [p for p in path.iterdir() if p.name not in {".", ".."}]
    return entries[0] if len(entries) == 1 and entries[0].is_dir() else path

def copytree_contents(src: Path, dst: Path) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    for child in src.iterdir():
        target = dst / child.name
        if child.is_dir():
            shutil.copytree(child, target, dirs_exist_ok=True)
        else:
            shutil.copy2(child, target)

def make_executable(path: Path) -> None:
    if path.exists():
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

def write_toolchain_file(root: Path, platform: str) -> None:
    tc = root / "toolchain"
    target = "x86_64-windows-gnu" if platform == "windows" else "x86_64-linux-gnu"
    zig = "${CMAKE_CURRENT_LIST_DIR}/zig/zig.exe" if platform == "windows" else "${CMAKE_CURRENT_LIST_DIR}/zig/zig"
    text = (
        "# Generated by GekkoAOT portable release staging.\n"
        f'set(CMAKE_C_COMPILER "{zig}" "cc" "-target" "{target}")\n'
        f'set(CMAKE_CXX_COMPILER "{zig}" "c++" "-target" "{target}")\n'
        "set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)\n"
    )
    (tc / "gekkoaot-zig.cmake").write_text(text, encoding="utf-8")

def bootstrap(root: Path, platform: str) -> None:
    platform = platform.lower()
    if platform not in URLS:
        raise RuntimeError(f"unsupported platform: {platform}")

    tc = root / "toolchain"
    bin_dir = tc / "bin"
    licenses = tc / "licenses"
    bin_dir.mkdir(parents=True, exist_ok=True)
    licenses.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="gekkoaot-portable-") as td_s:
        td = Path(td_s)
        for name in ("cmake", "ninja", "zig"):
            url = URLS[platform][name]
            suffix = ".zip" if url.endswith(".zip") else (".tar.xz" if url.endswith(".tar.xz") else ".tar.gz")
            archive = td / f"{name}{suffix}"
            extract_dir = td / f"{name}-extract"
            download(url, archive)
            extract(archive, extract_dir)
            src = single_root(extract_dir)

            if name == "cmake":
                dst = tc / "cmake"
                if dst.exists():
                    shutil.rmtree(dst)
                copytree_contents(src, dst)
            elif name == "zig":
                dst = tc / "zig"
                if dst.exists():
                    shutil.rmtree(dst)
                copytree_contents(src, dst)
            else:
                expected = "ninja.exe" if platform == "windows" else "ninja"
                exe = next((p for p in src.rglob(expected) if p.is_file()), None)
                if not exe:
                    raise RuntimeError("ninja executable not found")
                shutil.copy2(exe, bin_dir / expected)
                make_executable(bin_dir / expected)

    for p in (tc / "cmake/bin/cmake", tc / "cmake/bin/ctest", tc / "cmake/bin/cpack", tc / "zig/zig"):
        make_executable(p)

    write_toolchain_file(root, platform)
    (licenses / "PORTABLE-TOOLCHAIN-NOTICE.txt").write_text(
        f"GekkoAOT portable toolchain\n\n"
        f"CMake {CMAKE_VERSION} - BSD-3-Clause - https://cmake.org/\n"
        f"Ninja {NINJA_VERSION} - Apache-2.0 - https://ninja-build.org/\n"
        f"Zig {ZIG_VERSION} - MIT - https://ziglang.org/\n\n"
        "See THIRD_PARTY_NOTICES.md and component licenses for all other bundled software.\n",
        encoding="utf-8",
    )
    (tc / "bootstrap.txt").write_text(
        f"portable-toolchain-v1\nplatform={platform}\ncmake={CMAKE_VERSION}\nninja={NINJA_VERSION}\nzig={ZIG_VERSION}\n",
        encoding="utf-8",
    )
    print(f"[portable] base toolchain ready: {tc}")

def ignore_git(path: str, names: list[str]) -> set[str]:
    return {n for n in names if n in {".git", ".github"}}

def find_first(root: Path, patterns: tuple[str, ...]) -> Path | None:
    if not root.exists():
        return None
    candidates = [
        p for p in root.rglob("*")
        if p.is_file() and any(fnmatch.fnmatch(p.name, pat) for pat in patterns)
    ]
    candidates.sort(key=lambda p: (len(p.parts), len(str(p))))
    return candidates[0] if candidates else None

def capture_engine(root: Path, state: Path, platform: str, llvm_root: Path | None,
                   runtime_files: list[Path]) -> None:
    platform = platform.lower()
    tc = root / "toolchain"
    bin_dir = tc / "bin"
    lib_dir = tc / "lib"
    src_dir = tc / "src"
    licenses = tc / "licenses"
    for p in (bin_dir, lib_dir, src_dir, licenses):
        p.mkdir(parents=True, exist_ok=True)

    dol_src = state / "src/DolRecomp"
    if not (dol_src / "src/cpu/cpu.c").exists():
        raise RuntimeError(f"patched DolRecomp source missing: {dol_src}")

    dst_dol = src_dir / "DolRecomp"
    if dst_dol.exists():
        shutil.rmtree(dst_dol)
    shutil.copytree(dol_src, dst_dol, ignore=ignore_git)

    dol_name = "dolrecomp.exe" if platform == "windows" else "dolrecomp"
    dol = find_first(state / "build/DolRecomp", (dol_name,))
    if not dol:
        raise RuntimeError("prebuilt DolRecomp not found")
    shutil.copy2(dol, bin_dir / dol_name)
    make_executable(bin_dir / dol_name)

    bridge_patterns = ("gekkoaot-native-gx.dll",) if platform == "windows" else ("libgekkoaot-native-gx.so", "libgekkoaot-native-gx.so.*")
    bridge = find_first(state / "build/NativeGX-Aurora", bridge_patterns)
    if not bridge:
        raise RuntimeError("prebuilt AuroraGX bridge not found")
    shutil.copy2(bridge, bin_dir / bridge.name)
    make_executable(bin_dir / bridge.name)

    if platform == "windows":
        seen = set()
        bridge_root = state / "build/NativeGX-Aurora"
        for p in bridge_root.rglob("*.dll"):
            key = p.name.lower()
            if key not in seen:
                seen.add(key)
                shutil.copy2(p, bin_dir / p.name)
    else:
        seen = set()
        bridge_root = state / "build/NativeGX-Aurora"
        for p in bridge_root.rglob("*.so*"):
            if p.is_file() and p.name not in seen:
                seen.add(p.name)
                shutil.copy2(p, lib_dir / p.name)

    if llvm_root and llvm_root.exists():
        prof = llvm_root / ("bin/llvm-profdata.exe" if platform == "windows" else "bin/llvm-profdata")
        if prof.exists():
            shutil.copy2(prof, bin_dir / prof.name)
            make_executable(bin_dir / prof.name)
        if platform == "windows" and (llvm_root / "bin").exists():
            for p in (llvm_root / "bin").glob("*.dll"):
                if p.name.lower().startswith(("llvm", "lib", "zlib", "zstd")):
                    shutil.copy2(p, bin_dir / p.name)
        elif platform == "linux":
            # Homebrew llvm@20 does not bundle libc++ on Linux. Keep LLVM's
            # shared runtime here; compiler runtimes are supplied explicitly
            # with --runtime and copied below.
            copied = set()
            for p in llvm_root.rglob("libLLVM*.so*"):
                if not p.is_file() or p.name in copied:
                    continue
                copied.add(p.name)
                shutil.copy2(p, lib_dir / p.name)

    for runtime in runtime_files:
        if not runtime.exists() or not runtime.is_file():
            raise RuntimeError(f"portable runtime file missing: {runtime}")
        shutil.copy2(runtime, lib_dir / runtime.name)

    for source, prefix in ((state / "src/Aurora", "Aurora"), (dst_dol, "DolRecomp")):
        for name in ("LICENSE", "LICENSE.txt", "COPYING"):
            p = source / name
            if p.exists():
                shutil.copy2(p, licenses / f"{prefix}-{name}")
                break

    (tc / "engine.ready").write_text(
        f"gekkoaot-portable-engine-v1\nplatform={platform}\n"
        "dolrecomp=prebuilt\nauroragx=prebuilt\ngit-runtime=not-required\nsystem-compiler-runtime=not-required\n",
        encoding="utf-8",
    )
    print(f"[portable] captured engine into {tc}")

def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("bootstrap")
    b.add_argument("--root", required=True, type=Path)
    b.add_argument("--platform", required=True)

    c = sub.add_parser("capture-engine")
    c.add_argument("--root", required=True, type=Path)
    c.add_argument("--state", required=True, type=Path)
    c.add_argument("--platform", required=True)
    c.add_argument("--llvm-root", type=Path)
    c.add_argument("--runtime", action="append", type=Path, default=[])

    ns = ap.parse_args()
    if ns.cmd == "bootstrap":
        bootstrap(ns.root.resolve(), ns.platform.lower())
    else:
        capture_engine(
            ns.root.resolve(),
            ns.state.resolve(),
            ns.platform.lower(),
            ns.llvm_root.resolve() if ns.llvm_root else None,
            [runtime.resolve() for runtime in ns.runtime],
        )
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
